# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/martini/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),martini)

$(call add-radio-file-sha1-checked,radio/abl.img,318e3bec3b21002322b1acf6644f99c95926a785)
$(call add-radio-file-sha1-checked,radio/aop.img,10c2860d988bf81a0e764b4af2a4650735866021)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,87b2316a564e71bfb96343354f8c7fe880124ee3)
$(call add-radio-file-sha1-checked,radio/cpucp.img,3e028b9b4df9946956cd82693857855202132429)
$(call add-radio-file-sha1-checked,radio/devcfg.img,9ed46c5c909eb11900252e6708044e6ee3d9dc44)
$(call add-radio-file-sha1-checked,radio/dsp.img,634718247c9670c0c2aab842804ea74c3f274396)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,3f60181b70b602e8bf08dc60d7dcedb271c2d992)
$(call add-radio-file-sha1-checked,radio/hyp.img,b20adfdbac748b52cafe32e7acf41aee75296a00)
$(call add-radio-file-sha1-checked,radio/imagefv.img,4e1b8a5b9ac5647456707dc5937c6e4ab9012f11)
$(call add-radio-file-sha1-checked,radio/keymaster.img,e8957a9b82df355d7ed4989a8b08a98141859e69)
$(call add-radio-file-sha1-checked,radio/modem.img,3a0c9e5894e68f0173bb815b957577f1d9cb52b2)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,f5c87e40648b39aac2715dd6ba06ebdd89e1c574)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,bcd981d0d975e649c1b4d2a741ee0bce1ca905bb)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,236e14df0f833e6e908d4234759ee5ef229acd3d)
$(call add-radio-file-sha1-checked,radio/qupfw.img,1668916e6152c6d9579dd3d476b4f2d49d6428d6)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,a73524dcce8673c51cf9a4e539005a92490018d7)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,ef73d8100616f74fb9c69b46906a5144cd0a4a11)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,6cb66c5d85befd5eb60e8dc54982317a98413c76)
$(call add-radio-file-sha1-checked,radio/xbl.img,84dc7c571db8fd5a026d21c2c4419db09a6255d1)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,7807581e3a355797f4afa8962a3ce1f04af2afff)

endif
