# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/martini/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),martini)

$(call add-radio-file-sha1-checked,radio/abl.img,adcc4777996f8d12ec0f8641609c1840f7ff9c29)
$(call add-radio-file-sha1-checked,radio/aop.img,5ae20a4b113bc1ca467497f41eb583c43040de1f)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,bdd1a35373dc1dc96cb9374918c537337d2197a1)
$(call add-radio-file-sha1-checked,radio/cpucp.img,8c968714d6803321756bdab56216e3a1fb9a71fa)
$(call add-radio-file-sha1-checked,radio/devcfg.img,5825162379fd0e65b083d0a41ec26f20394a4d14)
$(call add-radio-file-sha1-checked,radio/dsp.img,634718247c9670c0c2aab842804ea74c3f274396)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,d224daf9dba3b8f6e18d95ef6e5bcee2ef45c612)
$(call add-radio-file-sha1-checked,radio/hyp.img,50fb05644c9152383832f9c0330df862e9c45d9d)
$(call add-radio-file-sha1-checked,radio/imagefv.img,74284c36d29c5b97202c2063d518008c8dda5b19)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f4c6857f7937eab4339a3cc54260090fd21cd215)
$(call add-radio-file-sha1-checked,radio/modem.img,857f3d416948c53ea07c4835cc89bd20d06726ad)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,ac4e8bd4dbf9a8809a49e4b4086a6c60b7f5fe14)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,bcd981d0d975e649c1b4d2a741ee0bce1ca905bb)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,f626278a739a4b4a035db7529359efcb167aef36)
$(call add-radio-file-sha1-checked,radio/qupfw.img,2878ef128e3676045004c1db563f7a1a345c1871)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,93d105985bf863c37fe78f80e519707e3e5d13bc)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,c5efad9f8b365067336c16707ab3037a9fbe8f2d)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,8c374881e797d5b2c7bb58012c91992d1a7ceee8)
$(call add-radio-file-sha1-checked,radio/xbl.img,54a378d0475e8da1d5105a5d976a4defb4873aac)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a9884d6ef7b1bc3341a6c393461121f4fb76fdf4)

endif
