# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/martini/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),martini)

$(call add-radio-file-sha1-checked,radio/abl.img,adcc4777996f8d12ec0f8641609c1840f7ff9c29)
$(call add-radio-file-sha1-checked,radio/aop.img,fd2d6ce2d9967011390e3c3ef942949089246a90)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,d70fab20f382373d3a47ebbbc78ca31c29e055e0)
$(call add-radio-file-sha1-checked,radio/cpucp.img,59147c801f5c8b9eb4295ed7cdff4cd2aae113cc)
$(call add-radio-file-sha1-checked,radio/devcfg.img,cff53eeb22772057cdfe278bcfd743742c90f3e2)
$(call add-radio-file-sha1-checked,radio/dsp.img,634718247c9670c0c2aab842804ea74c3f274396)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,1227ad41f2eed8c91cc55ee823b4ff5800fca187)
$(call add-radio-file-sha1-checked,radio/hyp.img,662155be03c6d39953a8c3ac88da334dcd7c464f)
$(call add-radio-file-sha1-checked,radio/imagefv.img,0730a53ac8b24b21dd4bd5ed77f48a1c67adee13)
$(call add-radio-file-sha1-checked,radio/keymaster.img,28c08644f41bee84aa0c037996533910fca37e8f)
$(call add-radio-file-sha1-checked,radio/modem.img,886d0aa18dfb4f16d98c2eb98f88697b6b57fd7d)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,311f6f1885efaed6ecad2f6dee08feeb9b146d49)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,bcd981d0d975e649c1b4d2a741ee0bce1ca905bb)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,52099bbb80d820ea1c155f1ca699b6ebedf802e5)
$(call add-radio-file-sha1-checked,radio/qupfw.img,f590b1598996e2fd39e2af4e727cb887d36df140)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,550542afac7a2851bffa212a04bab52d377ade1b)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,a6cb62955e24b99f53e08a026f925eecebbac2e2)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,e40d9c6eed955f250f0cfdb1688493a30d5655d9)
$(call add-radio-file-sha1-checked,radio/xbl.img,9a4d21b98bdbdca6433c298a52922051d7422a02)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,cbcbc54803078765308d6c17490757a4a4013f44)

endif
